### ISSUE TITLE
no sound in chrome 65+?

### ISSUE THREAD

**Issue by coderofsalvation** [usdivad/mesing#1]
Hi very interesting project, but did you test this in more recent versions of chrome?

**Comment by usdivad** [comment]
Oof I hadn't since [this update](http://www.gamasutra.com/view/news/317698/Chrome_update_kills_audio_on_many_webbased_games.php) but will look into it soon -- thanks for the heads up!

**Comment by usdivad** [comment]
Just tried with Chrome 69 (including with the "--disable-features=AutoplayIgnoreWebAudio" flag), and all seems to be working, so closing this issue for now.
